name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with: {python-version: '3.10'}
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
        restore-keys: ${{ runner.os }}-pip-
    - run: pip install .[test]
    - run: pytest tests/ -v -m "not integration" --maxfail=1

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with: {python-version: '3.10'}
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
        restore-keys: ${{ runner.os }}-pip-
    - run: pip install .[test]
    - run: pytest tests/ -v -m integration --maxfail=1
